version: '3.0'
services:
  main:
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    environment:
      - JUPYTER_TOKEN=passwd # TODO: Change the token
    user: ${UID}:${GID}
    working_dir: ${HOME}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - ${HOME}:${HOME}
    ports:
      - 8888:8888
      - 16000-16020:16000-16020
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
