version: '3.0'
services:
  code-server:
    hostname: code-server
    container_name: code-server
    image: sharockys/vscode-py-cuda
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.coder:/var/run/coder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    networks:
      - code_server_network
    environment:
      - DEVURL_HOST=code-server.localhost

  caddy:
    container_name: caddy
    hostname: caddy
    image: caddy:alpine
    links:
      - "code-server:code"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "../../caddy_config:/etc/caddy"
      - "../../certs:/certs"
    networks:
      - code_server_network

networks:
  code_server_network:
