name: Create and publish a Docker iamge

on:
  schedule:
    - cron: "0 23 28 * *"
  push:
    branches:
      - "main"

jobs:
  build-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:latest
          target: notebook

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: curl
        run: curl -X POST https://api2.pushdeer.com/message/push\?pushkey\=${{ secrets.PUSHDEER_TOKEN }}\&text\=notebook-cuda-image-built

  build-vscode:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vscode-py-cuda:latest
          target: vscode-py

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: curl
        run: curl -X POST https://api2.pushdeer.com/message/push\?pushkey\=${{ secrets.PUSHDEER_TOKEN }}\&text\=vscode-py-cuda-image-built
